import { BusinessProfile, Client, Invoice, Payment, ProductService, Quotation, ActivityLog, DocumentItem } from '../types';

export const initialBusinessProfile: BusinessProfile = {
  companyName: 'TrustLayerLabs',
  legalName: 'TrustLayer Technologies Pvt Ltd',
  logoUrl: '/ttlslogo.png',
  headerImageUrl: '/header.png',
  address: {
    line1: 'Building 4B, Mindspace IT Park, Hitec City',
    city: 'Hyderabad',
    state: 'Telangana',
    pin: '500081',
    country: 'India',
  },
  gstin: '36AAACT8451A1ZQ',
  pan: 'AAACT8451A',
  cin: 'U72900TG2024PTC184920',
  website: 'https://www.trustlayerlabs.co.in',
  email: 'billing@trustlayerlabs.co.in',
  phone: '+91 40 4859 2000',
  whatsapp: '+91 98490 12345',
  bankDetails: {
    bankName: 'HDFC Bank Ltd',
    accountNumber: '50200084729104',
    ifscCode: 'HDFC0000045',
    branch: 'Hitec City Branch, Hyderabad',
    accountName: 'TrustLayer Technologies Pvt Ltd',
  },
  upiId: 'trustlayerlabs@hdfcbank',
  branding: {
    primaryColor: '#0B132B',
    secondaryColor: '#0066FF',
    slogan: 'THE VERIFIED TRUST LAYER',
    footerText: 'TRUST IS NOT ASSUMED. TRUST IS TESTED. TRUST IS VERIFIED.',
  },
};

export const initialClients: Client[] = [
  {
    id: 'cli-001',
    companyName: 'Acme Cyber Systems Pvt Ltd',
    contactPerson: 'Vikram Malhotra',
    designation: 'Chief Information Security Officer',
    email: 'vikram.malhotra@acmecyber.com',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    billingAddress: {
      line1: 'Plot 12, Cyber Gateway, Madhapur',
      city: 'Hyderabad',
      state: 'Telangana',
      pin: '500081',
      country: 'India',
    },
    gstin: '36AABCA1234F1ZM',
    pan: 'AABCA1234F',
    outstandingBalance: 0,
    status: 'Active',
    createdAt: '2026-09-01',
  },
  {
    id: 'cli-002',
    companyName: 'FinTech Secure Solutions India',
    contactPerson: 'Ananya Roy',
    designation: 'VP of Engineering',
    email: 'ananya.roy@fintechsecure.in',
    phone: '+91 91234 56789',
    whatsapp: '+91 91234 56789',
    billingAddress: {
      line1: 'Tower 3, Financial District, Gachibowli',
      city: 'Hyderabad',
      state: 'Telangana',
      pin: '500032',
      country: 'India',
    },
    gstin: '36AAACF5678K1ZP',
    pan: 'AAACF5678K',
    outstandingBalance: 0,
    status: 'Active',
    createdAt: '2026-09-05',
  },
];

export const initialServices: ProductService[] = [
  {
    id: 'srv-001',
    name: 'VAPT (Web & API Penetration Testing)',
    description: 'Web application and REST API penetration testing with comprehensive exploit analysis and OWASP Top 10 remediation.',
    unit: 'Project',
    unitPrice: 150000,
    taxPercent: 18,
    deliverables: 'Executive Audit Report, Exploit Proof-of-Concept, Code Remediation Roadmap',
  },
  {
    id: 'srv-002',
    name: 'ISO 27001 Security Audit & Architecture Assessment',
    description: 'Complete architecture security assessment, threat modeling audit, and ISO 27001 readiness review.',
    unit: 'Project',
    unitPrice: 200000,
    taxPercent: 18,
    deliverables: 'Architecture Audit Scorecard, Risk Register, Compliance GAP Analysis',
  },
  {
    id: 'srv-003',
    name: 'Cloud Infrastructure Security Hardening',
    description: 'AWS / Azure / GCP cloud posture assessment, IAM policy review, and CIS Benchmark compliance audit.',
    unit: 'Project',
    unitPrice: 120000,
    taxPercent: 18,
    deliverables: 'Cloud Infrastructure Scorecard, Automation Hardening Scripts',
  },
  {
    id: 'srv-004',
    name: 'Retainer Virtual CISO Advisory',
    description: 'Dedicated virtual CISO advisory, continuous vulnerability management, and incident response support.',
    unit: 'Month',
    unitPrice: 85000,
    taxPercent: 18,
    deliverables: 'Monthly Advisory Digest, Executive Briefings, 24/7 Hotline',
  },
];

const sampleItemsQuo1: DocumentItem[] = [
  {
    id: 'li-001',
    serviceId: 'srv-001',
    name: 'VAPT (Web & API Penetration Testing)',
    description: 'VAPT (Web & API Penetration Testing) - 2 Web Applications',
    quantity: 2,
    unit: 'Project',
    unitPrice: 150000,
    discountPercent: 0,
    taxPercent: 18,
    totalPrice: 354000,
  },
  {
    id: 'li-002',
    serviceId: 'srv-002',
    name: 'ISO 27001 Security Audit & Architecture Assessment',
    description: 'ISO 27001 Security Audit & Architecture Assessment',
    quantity: 1,
    unit: 'Project',
    unitPrice: 200000,
    discountPercent: 0,
    taxPercent: 18,
    totalPrice: 236000,
  },
];

const sampleItemsQuo2: DocumentItem[] = [
  {
    id: 'li-003',
    serviceId: 'srv-003',
    name: 'Cloud Infrastructure Security Hardening',
    description: 'Cloud Infrastructure Security Hardening (AWS & Azure)',
    quantity: 1,
    unit: 'Project',
    unitPrice: 120000,
    discountPercent: 0,
    taxPercent: 18,
    totalPrice: 141600,
  },
  {
    id: 'li-004',
    serviceId: 'srv-004',
    name: 'Retainer Virtual CISO Advisory',
    description: 'Retainer Virtual CISO Advisory (Quarterly Retainer)',
    quantity: 3,
    unit: 'Month',
    unitPrice: 85000,
    discountPercent: 0,
    taxPercent: 18,
    totalPrice: 300900,
  },
];

export const initialQuotations: Quotation[] = [
  {
    id: 'quo-001',
    number: 'TTL-QT-2026-001',
    clientId: 'cli-001',
    client: initialClients[0],
    issueDate: '2026-09-10',
    validUntil: '2026-10-10',
    currency: 'INR',
    currencySymbol: '₹',
    paymentTerms: '50% Advance upon PO, 50% upon audit delivery',
    items: sampleItemsQuo1,
    globalDiscount: 0,
    financials: {
      subtotal: 500000,
      itemDiscounts: 0,
      globalDiscount: 0,
      taxableAmount: 500000,
      cgst: 45000,
      sgst: 45000,
      igst: 0,
      roundOff: 0,
      grandTotal: 590000,
    },
    notes: 'Comprehensive web application VAPT and ISO 27001 gap analysis for Acme Cyber Systems.',
    terms: [
      '50% advance payment required upon PO confirmation.',
      'Audit reports delivered within 10 business days.',
      'Includes one complimentary re-test within 30 days.',
    ],
    templateId: 'trustlayer-labs',
    status: 'ACCEPTED',
    createdAt: '2026-09-10',
    updatedAt: '2026-09-12',
    signature: {
      type: 'draw',
      signatureDataUrl: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjUwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjx0ZXh0IHg9IjEwIiB5PSIzMCIgZm9udC1mYW1pbHk9IkN1cnNpdmUsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMjAiIGZpbGw9IiMwMDY2RkYiPlZpa3JhbSBNYWxob3RyYTwvdGV4dD48L3N2Zz4=',
      signedByName: 'Vikram Malhotra',
      signedByDesignation: 'CISO, Acme Cyber Systems',
      signedAt: '2026-09-12T10:30:00Z',
    },
    verification: {
      verificationId: 'VER-QT-849201',
      verificationUrl: 'http://localhost:3001/q/TTL-QT-2026-001',
      hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      isVerified: true,
      timestamp: '2026-09-10T09:00:00Z',
    },
  },
  {
    id: 'quo-002',
    number: 'TTL-QT-2026-002',
    clientId: 'cli-002',
    client: initialClients[1],
    issueDate: '2026-09-15',
    validUntil: '2026-10-15',
    currency: 'INR',
    currencySymbol: '₹',
    paymentTerms: 'Net 30 Days from invoice date',
    items: sampleItemsQuo2,
    globalDiscount: 0,
    financials: {
      subtotal: 375000,
      itemDiscounts: 0,
      globalDiscount: 0,
      taxableAmount: 375000,
      cgst: 33750,
      sgst: 33750,
      igst: 0,
      roundOff: 0,
      grandTotal: 442500,
    },
    notes: 'Multi-cloud AWS & Azure security hardening audit and 12-month retainer virtual CISO advisory.',
    terms: [
      'Payment terms: 30 days net from invoice date.',
      'Monthly security digest delivered by 5th of each month.',
    ],
    templateId: 'trustlayer-labs',
    status: 'SENT',
    createdAt: '2026-09-15',
    updatedAt: '2026-09-15',
    verification: {
      verificationId: 'VER-QT-849202',
      verificationUrl: 'http://localhost:3001/q/TTL-QT-2026-002',
      hash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
      isVerified: true,
      timestamp: '2026-09-15T11:00:00Z',
    },
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-001',
    number: 'TTL-INV-2026-001',
    quotationId: 'quo-001',
    clientId: 'cli-001',
    client: initialClients[0],
    issueDate: '2026-09-12',
    dueDate: '2026-09-27',
    currency: 'INR',
    currencySymbol: '₹',
    items: sampleItemsQuo1,
    globalDiscount: 0,
    financials: {
      subtotal: 716101.69,
      itemDiscounts: 0,
      globalDiscount: 0,
      taxableAmount: 716101.69,
      cgst: 64449.15,
      sgst: 64449.15,
      igst: 0,
      roundOff: 0,
      grandTotal: 845000,
    },
    status: 'PAID',
    amountPaid: 845000,
    amountDue: 0,
    paymentTerms: 'Immediate upon delivery of audit report',
    notes: 'Thank you for choosing TrustLayerLabs for your enterprise security requirements.',
    templateId: 'trustlayer-labs',
    createdAt: '2026-09-12',
    updatedAt: '2026-09-16',
    verification: {
      verificationId: 'VER-INV-849201',
      verificationUrl: 'http://localhost:3001/q/TTL-INV-2026-001',
      hash: 'a7164813aabe4fe2956bc11c84920194827164813aabe4fe2956bc11c8492019',
      isVerified: true,
      timestamp: '2026-09-12T11:00:00Z',
    },
  },
];

export const initialPayments: Payment[] = [
  {
    id: 'pay-001',
    invoiceId: 'inv-001',
    invoiceNumber: 'TTL-INV-2026-001',
    clientName: 'Acme Cyber Systems Pvt Ltd',
    amount: 845000,
    paymentDate: '2026-09-16',
    method: 'Bank Transfer',
    transactionId: 'TXN849201948201',
    notes: 'Full payment received via HDFC NEFT. Verified SHA-256 ledger.',
    createdAt: '2026-09-16',
  },
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: 'log-001',
    timestamp: '2026-09-16 14:30',
    user: 'Alex Rivera (Admin)',
    action: 'Payment Verified',
    documentNumber: 'TTL-INV-2026-001',
    documentType: 'payment',
    details: 'Payment of ₹8,45,000 recorded via NEFT (TXN849201948201). Invoice marked PAID.',
  },
  {
    id: 'log-002',
    timestamp: '2026-09-15 11:15',
    user: 'Priya Sharma (Sales Eng)',
    action: 'Quotation Sent',
    documentNumber: 'TTL-QT-2026-002',
    documentType: 'quotation',
    details: 'Quotation dispatched to FinTech Secure Solutions (ananya.roy@fintechsecure.in).',
  },
  {
    id: 'log-003',
    timestamp: '2026-09-12 10:30',
    user: 'Client (Vikram Malhotra)',
    action: 'E-Signature Executed',
    documentNumber: 'TTL-QT-2026-001',
    documentType: 'quotation',
    details: 'Quotation cryptographically signed by CISO Vikram Malhotra and converted to Invoice TTL-INV-2026-001.',
  },
];
